### ISSUE TITLE
Can't get LatLng values

### ISSUE THREAD

**Issue by Sphincz** [stephenbaidu/android-place-picker#2]
Hello again,

I still cant get Lat Long from getDoubleExtra to test with Logs :( It gives me 0.0 always :(

**Comment by stephenbaidu** [comment]
Okay, I will look into it right away.

**Comment by Sphincz** [comment]
Thank you very much for you support :smiley:

**Comment by Sphincz** [comment]
I think it's in PlaceApiRequest.java, details() method is never used, but whenever i call it, it says correct Lat Lng values, but not on onActivityResult (placeDetail.toString: ID correct, Description correct,<0.0, 0.0> ;)

**Comment by stephenbaidu** [comment]
Yeah. Am surprised I did not finish that part. Please hold on, am currently working on it. Thanks.

**Comment by Sphincz** [comment]
Sure sure :) i just want to help. I found your snippet very useful to me. Thank you very much :+1:

**Comment by stephenbaidu** [comment]
@Sphincz Please find the example on fetching the place details [here](https://github.com/stephenbaidu/android-place-picker/blob/master/demo/src/main/java/com/github/stephenbaidu/demo/MainActivity.java#L57). Sorry for the wait.

**Comment by Sphincz** [comment]
Thank you very much, its working flawlessly :smile: . No problems ;)

**Comment by stephenbaidu** [comment]
Great. You're welcome.
