### ISSUE TITLE
Array Index Out of bounds Exception

### ISSUE THREAD

**Issue by stripathi669** [stephenbaidu/android-place-picker#4]
Sometimes while typing the text of the address, I get following error and the app crashes:

```
ArrayIndexOutOfBoundsException (@AutocompleteTask:doInBackground:86) {AsyncTask #2}
```

**Comment by stephenbaidu** [comment]
Okay, I will look into it.

**Comment by stephenbaidu** [comment]
I cannot seem to be able to replicate the error. But I suspect it is as a result of the description not having a comma in it. Hence, below is a fix, please let me know if this works for you.

```
try {
    // Create a JSON object hierarchy from the results
    JSONObject jsonObj = new JSONObject(jsonResults.toString());
    JSONArray predsJsonArray = jsonObj.getJSONArray("predictions");

    // Extract the Place descriptions from the results
    resultList = new ArrayList<PlaceInfo>(predsJsonArray.length());
    for (int i = 0; i < predsJsonArray.length(); i++) {
        JSONObject place = predsJsonArray.getJSONObject(i);
        String id = place.getString("place_id");
        String[] descriptions = place.getString("description").split(", ", 2);
        String name = descriptions[0];
        String description = (descriptions.length > 1)? descriptions[1] : "";

        resultList.add(new PlaceInfo(id, name, description));
    }
} catch (JSONException e) {
    Log.e(LOG_TAG, "Cannot process JSON results", e);
} catch (Exception e) {
    Log.e(LOG_TAG, "Exception", e);
}
```

I also added a generic exception block to prevent the app from crashing in case of other unknown exceptions.

**Comment by stripathi669** [comment]
I have done the same thing on my end.

By the way, what other features should I expect in next release on Maven ?

**Comment by stephenbaidu** [comment]
Well, I do not really have much in mind. Am still thinking about the request you made #3 though. Feel free to suggest features you would like to see.

**Comment by stripathi669** [comment]
One more issue that I could see was that in the search view, the rows didn't wrap the place name if the name length was more than screen's.

**Comment by giorgiobasile** [comment]
Hi, I'm importing your library as gradle dependency, but unfortunately your fix in the AutocompleteTask class doesn't appear (I'm talking about the generic Exception catch). Could you please fix it?

P.s. If you need to reproduce the error, you can for instance just write 46 in the search box, this is how I got the ArrayIndexOutOfBoundsException

**Comment by stephenbaidu** [comment]
@giorgiobasile Have been trying to reproduce the error but could not. Just realised I have not pushed the update to jcenter. Will do that soon and sorry for the delay.

**Comment by stephenbaidu** [comment]
@giorgiobasile Please use the new version `1.1`. Closing this issue.
