### ISSUE TITLE
cannot find symbol onDetailFetch

### ISSUE THREAD

**Issue by bangive** [stephenbaidu/android-place-picker#5]
I use the demo in this project and android stuido show that error: cannot find symbol onDetailFetch

**Comment by stephenbaidu** [comment]
Okay, will take a look at it this evening.

**Comment by stephenbaidu** [comment]
@bangive From #6, I presume you have resolved this error. Please confirm. Thanks.

**Comment by bangive** [comment]
Thank you for your support, i don't use this library anymore. So i closed this issue.
