### ISSUE TITLE
how to get it work

### ISSUE THREAD

**Issue by bangive** [stephenbaidu/android-place-picker#6]
I use your demo and build it succesful then install to my android device Lenovo A319. But when i press button PICK A PLACE then enter keyword in search box it does not show any suggestion. Therefor i cannot pick any place

**Comment by stephenbaidu** [comment]
@bangive Did you set your API key? The `MainActivity.java` in the demo has the following line.

```
// Set your server api_key here
String api_key = "";
```

Please confirm if you provided your api key.

**Comment by bangive** [comment]
I set server key did not work
then android key did not work too.

**Comment by stephenbaidu** [comment]
Try replacing "YOUR-KEY-HERE" below, with your api key and see if you will get any results using a browser.

`https://maps.googleapis.com/maps/api/place/autocomplete/json?input=accra&key=YOUR-KEY-HERE`

**Comment by bangive** [comment]
i put android key get this:
`{
   "error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address xx.xx.x.xx, with empty referer",
   "predictions" : [],
   "status" : "REQUEST_DENIED"
}`

When put server key or browser key it show info. But i think those key is for request from server and browser not for android

**Comment by stephenbaidu** [comment]
Please follow the stackoverflow answer [here](http://stackoverflow.com/a/24303056/4465748) to create a server key. Hope this helps.

**Comment by bangive** [comment]
Thank you for your support, i don't use this library anymore. So i closed this issue.
