### ISSUE TITLE
Getting lat long 0.0

### ISSUE THREAD

**Issue by DharmbirChoudhary** [stephenbaidu/android-place-picker#7]
Hi, 

I used your library and working like charm. Thanks for your support and library.

I'm novice in android and don't have deep knowledge so i can't identify this error. So it would be great if you can help me to find out lat long.

I'm getting a issue which is getting Lat & Long = 0.0, even i'm getting proper address.

So could you help me 

Power Plant V.K.I. Area, Sector-9, Vishwakarma Industrial Area, Jaipur, Rajasthan, India
=====PlacePicker=====﹕ Longitue : 0.0
=====PlacePicker=====﹕ Latitude : 0.0
=====PlacePicker=====﹕ ChIJSf4kMUaybTkRS_Ji_aGgVGI: <Power Plant V.K.I. Area, Sector-9, Vishwakarma Industrial Area, Jaipur, Rajasthan, India> (0.0, 0.0)

Thanks & Regards
Dharmbir Singh

**Comment by stephenbaidu** [comment]
@DharmbirChoudhary I was able to reproduce the error. Currently looking into it.

**Comment by stephenbaidu** [comment]
@DharmbirChoudhary It turns out it was not an error. The longitude and latitude are not available until you run 

```
apiKey = ""; // Your api key here
placeId = "ChIJSf4kMUaybTkRS_Ji_aGgVGI"; // Power Plant V.K.I. Area, Sector-9, Vishwakarma Industrial Area, Jaipur, Rajasthan, India

PlacePicker.fetchDetails(apiKey, placeId, new PlacePicker.OnDetailFetched() {
    @Override
    public void completed(PlaceDetail placeInfoDetail) {
        Log.v("Longitude: ", placeInfoDetail.longitude.toString());
        Log.v("Latitude: ", placeInfoDetail.latitude.toString());
    }
});
```

**Comment by DharmbirChoudhary** [comment]
Thanks alot stephenbaidu, I got it, i really appreciate your help and support.

**Comment by stephenbaidu** [comment]
You're welcome @DharmbirChoudhary
